import { useEffect, useState } from 'react';
import dynamic from 'next/dynamic';
import { KPICard } from '../components/KPICard';
import { Sidebar } from '../components/Sidebar';
import { useDashboardData } from '../hooks/useDashboardData';
import Head from 'next/head';

const BarChart = dynamic(() => import('../components/BarChart'), { ssr: false });
const LineChart = dynamic(() => import('../components/LineChart'), { ssr: false });
const PieChart = dynamic(() => import('../components/PieChart'), { ssr: false });
const DoughnutChart = dynamic(() => import('../components/DoughnutChart'), { ssr: false });
const RadarChart = dynamic(() => import('../components/RadarChart'), { ssr: false });

export default function Dashboard() {
  const {
    filters,
    setFilters,
    filterOptions,
    summary,
    records,
    insight,
    loadingInsight,
    generateInsight
  } = useDashboardData();

  const [currentDate, setCurrentDate] = useState('');

  useEffect(() => {
    setCurrentDate(new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'short', day: 'numeric' }));
  }, []);

  return (
    <div className="dashboard-container">
      <Head>
        <title>Market Intelligence Dashboard | CMI</title>
      </Head>

      <Sidebar 
        filters={filters} 
        setFilters={setFilters} 
        filterOptions={filterOptions} 
        onGenerateInsight={generateInsight}
        loadingInsight={loadingInsight}
      />

      <main className="main-content">
        <header>
          <div>
            <h1>Vaccine Market Analytics</h1>
            <p>Comprehensive analysis of global market trends, pricing strategies, and regional distribution.</p>
          </div>
          <div style={{ textAlign: 'right', fontSize: '0.9rem', color: 'var(--text-secondary)' }}>
            <strong>Date:</strong> {currentDate} <br/>
            <strong>Report ID:</strong> VAX-2026-Q1
          </div>
        </header>

        {/* AI Insight Section */}
        {insight && (
          <div className="ai-insight">
            <h3>
              <span style={{ fontSize: '1.2rem', marginRight: '8px' }}>✦</span> 
              Executive Market Summary
            </h3>
            <div className="ai-text">
              {insight}
            </div>
            <div style={{ marginTop: '15px', fontSize: '0.75rem', color: 'var(--text-secondary)', fontStyle: 'italic' }}>
              Generated by Gemini AI • Confidential • Internal Use Only
            </div>
          </div>
        )}

        {/* KPIs */}
        <div className="kpi-grid">
          <KPICard title="Total Market Valuation" value={summary?.marketSizeTotal ? '$' + (summary.marketSizeTotal / 1000000).toFixed(1) + 'M' : '$0'} trend={12.5} />
          <KPICard title="CAGR (Compound Annual Growth)" value={summary?.cagr ? summary.cagr.toFixed(2) + '%' : '0.00%'} trend={2.1} />
          <KPICard title="Average Unit Price (ASP)" value={summary?.avgPrice ? '$' + summary.avgPrice.toFixed(2) : '$0.00'} trend={-0.5} />
          <KPICard title="Active Markets" value={filterOptions.regions?.length?.toString() || '0'} />
        </div>

        {/* Charts */}
        <div className="chart-grid">
          <div className="card" style={{ gridColumn: 'span 2' }}>
            <h3>Market Size Trajectory (Year-over-Year)</h3>
            <div style={{ height: '350px' }}><LineChart data={records} /></div>
          </div>
          <div className="card">
            <h3>Regional Market Share</h3>
            <div style={{ height: '300px', display: 'flex', justifyContent: 'center' }}><DoughnutChart data={records} /></div>
          </div>
          <div className="card">
            <h3>Revenue by Country</h3>
            <div style={{ height: '300px' }}><BarChart data={records} /></div>
          </div>
          <div className="card">
            <h3>Brand Competitive Landscape</h3>
            <div style={{ height: '300px', display: 'flex', justifyContent: 'center' }}><PieChart data={records} /></div>
          </div>
          <div className="card">
            <h3>Pricing Strategy Analysis</h3>
            <div style={{ height: '300px', display: 'flex', justifyContent: 'center' }}><RadarChart data={records} /></div>
          </div>
        </div>
      </main>
    </div>
  );
}
